// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class NewAchievmentRessource
{
        public const string achievement_not_bad_for_a_newbie = "CgkI-8jn6L0aEAIQAQ"; // <GPGSID>
        public const string achievement_getting_better = "CgkI-8jn6L0aEAIQAg"; // <GPGSID>
        public const string achievement_a_rising_star = "CgkI-8jn6L0aEAIQBg"; // <GPGSID>
        public const string achievement_gotta_start_somewhere = "CgkI-8jn6L0aEAIQBA"; // <GPGSID>
        public const string achievement_got_a_promotion = "CgkI-8jn6L0aEAIQAw"; // <GPGSID>
        public const string achievement_true_groover = "CgkI-8jn6L0aEAIQBQ"; // <GPGSID>

}

